version: "2"
services:
  ntopng:
    image: qdzlug/ntopng:10.2
    restart: always         
    depends_on:
      - redis
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5556:5556"
      - "2055:2055/udp"
  redis:
    image: qdzlug/redis:10.0
    restart: always         
    volumes:
      - redis-data:/data
volumes:
    redis-data:
      driver: "local"
