version: "3"
services:
  nprobe:
    build: ./nprobe-docker
    restart: always         
    depends_on:
      - redis
    ports:
      - "5556:5556"
      - "2055:2055/udp"
  ntopng:
    build: ./ntopng-docker
    restart: always         
    depends_on:
      - nprobe
      - elasticsearch
    ports:
      - "3000:3000"
      - "3001:3001"
  redis:
    build: ./redis
    restart: always         
    volumes:
      - redis-data:/data
  elasticsearch:
    build:
      context: elasticsearch/
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  logstash:
    build:
      context: logstash/
    restart: always
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
    redis-data:
      driver: "local"
    elasticsearch-data:
      driver: "local"
